In [30]:
not 0


True

In [68]:
import torch
from bitarray import bitarray

neighbors = torch.tensor([
    [1, 2],
    [0, -1],
    [0, -1],
], dtype=torch.int)

visited = bitarray([1, 1, 0])

def not_in_visited(vertex):
    return -1 if visited[vertex] else vertex

current_layer = torch.tensor([1, 2], dtype=torch.int)
flattened = neighbors[current_layer].flatten().unique()
flattened[flattened != -1]
next_layer = flattened.apply_(not_in_visited)[flattened != -1]
next_layer

tensor([], dtype=torch.int32)

In [80]:
from bitarray import bitarray
import torch

visited = torch.full(size=(10,), fill_value=0, dtype=torch.bool)
visited[torch.tensor([1, 2, 3], dtype=torch.int)] = 1

print(visited)

"""
testbitarray = bitarray(100)
testbitarray.setall(0)

testbitarray[[47, 83]] = 1

testbitarray
"""

tensor([False,  True,  True,  True, False, False, False, False, False, False])


In [17]:
from bitarray import bitarray

test = bitarray(200)
test.setall(0)  

'big'

In [1]:
def bin_search_loc_in_prefix_sum(prefix_sum: list[int], loc: int) -> int:
    """
    Returns the largest index i such that prefix_sum[i] <= loc
    """
    l, r = 0, len(prefix_sum) - 1
    while l < r:
        mid = (l + r + 1) // 2
        if prefix_sum[mid] <= loc:
            l = mid
        else:
            r = mid - 1
    return l

arr1 = [0, 10, 16, 18, 23, 30, 37]
print(bin_search_loc_in_prefix_sum(arr1, 0))
print(bin_search_loc_in_prefix_sum(arr1, 1))
print(bin_search_loc_in_prefix_sum(arr1, 10))
print(bin_search_loc_in_prefix_sum(arr1, 20))

0
0
1
3


In [6]:
import torch

# Your tensor
tensor1 = torch.tensor([
    [1, 0, 1],
    [0, 1, 1],
    [1, 0, 0]
])

testmask = torch.tensor([True, False, True])

torch.any(tensor1[testmask], dim=0)

tensor([ True, False,  True])

In [6]:
import torch
from bitarray import bitarray

test_visited = torch.zeros(10, dtype=torch.bool)
test_tensor = torch.tensor([3, 4, 6, 7, 8])

# Set all indices marked in test_tensor in test_visited to 1
test_visited[test_tensor] = 1
test_visited

tensor([False, False, False,  True,  True, False,  True,  True,  True, False])

In [29]:
import torch
from bitarray import bitarray

testba = bitarray([1, 0, 1, 1])
testba[bitarray([0, 0, 1])]

IndexError: bitarray length is 4, but mask has length 3

In [1]:
from bitarray import bitarray

test = bitarray([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])
testmask = bitarray([1, 1, 0, 0, 0, 0, 0, 0, 1, 1])

test[testmask]

bitarray('0011')

In [36]:
import torch
from bitarray import bitarray

testba = bitarray(torch.tensor([1, 0, 0, 1], dtype=torch.bool))
testba

TypeError: only integer tensors of a single element can be converted to an index

In [12]:
import torch
from bitarray import bitarray

tens = torch.tensor([
    [1, 0, 0, 1],
    [0, 1, 0, 0],
    [1, 1, 0, 0],
    [0, 0, 0, 1],
], dtype=torch.bool)

test1 = torch.any(tens, dim=0)
testrecord = bitarray([0, 1, 1, 0])
test1 and testrecord

RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [13]:
import torch

test2dtens = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

testarr = test2dtens[1]
testarr[0] = 10
test2dtens

tensor([[ 1,  2,  3],
        [10,  5,  6],
        [ 7,  8,  9]])